services:
  app:
    build: .
    container_name: election-reminders-v1
    ports:
      - "8443:8443"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - election-reminder-network

  postgres:
    image: postgres:17.4
    container_name: election-reminder-postgres-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - election-reminder-network

networks:
  election-reminder-network:


volumes:
  pgdata:
